### ISSUE TITLE
please relinquish the "sails-sqlserver" npm module name

### ISSUE THREAD

**Issue by tjwebb** [jaredfromsubway/sails-sqlserver#1]
You don't seem to be maintaining this project, and I'd like to publish updates to the module.

**Comment by jaredfromsubway** [comment]
Yeah, sure thing.  Are you looking to republish your sails-mssql branch over here?  

I should have some time for a couple PR's this week.  It'd be nice if we could prioritize some issues.   Couple of things off the top of my head:

- "skip" is currently supported by an innefficient sub-query.  For newer versions of sqlserver this should be using OFFSET.

- " is getting stripped and breaks stuff. All of field preparation stuff probably needs to start using sql parameters.

**Comment by tjwebb** [comment]
Yea, I got all the waterline-adapter-tests passing against my fork, and I added links to it in the official Waterline docs. If you're still interested in maintaining the adapter I'm happy to keep you on as an owner of the npm module; another sails-mssql developer (https://github.com/Seich) and myself were unsure what the status was so we blazed our own trail a bit.

**Comment by jaredfromsubway** [comment]
Remove.

**Comment by tjwebb** [comment]
I see, thanks. I'll add you as a contributor.

**Comment by mikermcneil** [comment]
@tjwebb @jaredfromsubway thanks for working together and doing such a great job, guys.

**Comment by tjwebb** [comment]
Thanks Mike!
